[package]
name = "timespec"
version = "1.5.1"
authors = ["Fenhl <fenhl@fenhl.net>"]
edition = "2021"

[lib]
name = "timespec"
path = "src/lib.rs"

[[bin]]
name = "timespec"
path = "src/main.rs"
doc = false
test = false
bench = false

[[bin]]
name = "sleeptill"
doc = false
test = false
bench = false

[dependencies]
chrono = "0.4"
chrono-tz = "0.6"
lazy-regex = "2"
thiserror = "1"
time = "0.1" # for compatibility with chrono

[dependencies.structopt]
version = "0.3"
features = ["paw"]

[dependencies.wheel]
git = "https://github.com/fenhl/wheel"
branch = "main"
