[package]
name = "timespec"
version = "1.5.0"
authors = ["Fenhl <fenhl@fenhl.net>"]
edition = "2018"

[lib]
name = "timespec"
path = "src/lib.rs"

[[bin]]
name = "timespec"
path = "src/main.rs"
doc = false
test = false
bench = false

[[bin]]
name = "sleeptill"
doc = false
test = false
bench = false

[dependencies]
chrono = "0.4"
chrono-tz = "0.5"
regex = "1"
time = "0.1"

[dependencies.derive_more]
version = "0.99"
default-features = false
features = ["from"]

[dependencies.structopt]
version = "0.3"
features = ["paw"]

[dependencies.wheel]
git = "https://github.com/fenhl/wheel"
branch = "main"
